# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Paweł Pindel | .NET - Azure - Software Development"

# A description of your site for social meta tag, search engines, and feed.xml
description: "NETSHARPDEV is a developer blog about Azure, .NET and Architecture. Here you can read some great posts of Paweł Pindel, Software Engineer at Gravity9 and NETSharp Development."

# Tagline near the site title
tagline: "Opinions, thoughts, solutions"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ''

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://netsharpdev.com"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/    
  - text: Portfolio
    url: /portfolio/
  - text: Archives
    url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: netsharpdev

# Author information - author info at the bottom of the post
author_name: "Paweł Pindel"
author_bio: "My name is Paweł Pindel, Software Engieer and Technical Leader, Microsoft Technologies enthusiast. Working currently at gravity9. 
I am here to share my knowledge and discuss with you."
author_url: "https://netsharpdev.com"
author_location: "Kraków, Poland"
author_image: /images/author.jpeg

# Sidebar Add banner
banner_url: "https://netsharpdev.com"
banner_image: 

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "https://netsharpdev.us4.list-manage.com/subscribe/post?u=1f7778d6547c8d4ffc8ac19cd&amp;id=6914607cb8"

# Social links in the site footer
twitter_username: "netsharpdev"
facebook_username: "pawel.pindel"
github_username: "netsharpdev"
codepen_username: "netsharpdev"
# medium_username: "@netsharpdev"
# instagram_username: "pindelpawel"
linkedin_username: "pawelpindel"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
